# Intent definition for Calendar skill
#
#  (c) A. Dominik, 2020
#
skill = "ADoSnipsWakeup"
developer = "andreasdominik"


[inventory]
intents = ["wakeupCall", "wakeupDelete", "wakeupSetRingtone"]
slots = ["wakeup_time", "ringtone"]


# define slots:
# Types: "Any", "ListOfValues", "Time", "Duration", "Currency", "Number", "Ordinal"
#
[wakeup_time]
slot_type = "Time"

# keywords for slide shows:
#
[ringtone]
slot_type = "ListOfValues"

        [ringtone.synonyms]
        "birds" = ["Vögeln", "Vögel", "Vogelgesang", "Vogelgezwitscher", "Wald", "Natur"]
        "concerto" = ["Beethoven? Violinkonzert", "Violinkonzert von Beethoven", "Violinkonzert", "Jehudi Menuhin"]
        "tschaikowski" = ["Tschaikowski", "Elegie", "Streichorchester", "Serenade für Streicher"]
        "moonlight" = ["Mondscheinsonate", "Mondschein Sonate"]
        "schumann" = ["Träumerei", "Robert Schumann", "Schumann"]
        "annoying" = ["Geklingel", "Klingelton", "Klingel"]


# define phrases for intent recognition:
# exact, regex, part
#
[wakeupCall]
wakeup_a = "partial: <<Bitte|>> stelle den Wecker <<bitte|>> auf <<wakeup_time>> mit <<>> <<>> <<ringtone>>"
wakeup_b = "partial: <<Bitte|>> stelle den Wecker <<bitte|>> auf <<wakeup_time>>"
wakeup_c = "partial: <<Bitte|>> wecke mich <<bitte|>> <<wakeup_time>> mit <<>> <<ringtone>>"
wakeup_d = "partial: <<Bitte|>> wecke mich <<bitte|>> <<wakeup_time>>"

[wakeupSetRingtone]
ringtone_a = "partial: wecke mich mit <<ringtone>>"
ringtone_b = "partial: verwende <<bitte|>> <<ringtone>> als <<Klingelton|Wecker>>"
ringtone_c = "partial: stelle <<bitte|>> den Klingelton auf <<ringtone>>"

[wakeupDelete]
wakeup_del_a = "partial: <<Bitte|>> schalte <<bitte|>> den Wecker <<bitte|>> aus"
wakeup_del_b = "partial: <<Bitte|>> lösche den Wecker <<bitte|>>"
